version: "3.9"

services:
  db:
    image: postgres:15
    container_name: dashboard_db
    restart: always
    environment:
      POSTGRES_DB: dashboard_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: dashboard_backend
    restart: always
    environment:
      DB_NAME: dashboard_db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432
      API_PORT: 5000
      SECRET_KEY: super-secret-key-change-this
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
